<?php
/**
 * Created by PhpStorm.
 * User: Hpp
 * Date: 27.06.2018
 * Time: 0:46
 */

namespace common\models;


use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

class ActiveRecord extends \yii\db\ActiveRecord
{
    public function behaviors()
    {
        parent::behaviors(); // TODO: Change the autogenerated stub
        return
            [
                ['class' => TimestampBehavior::className(),
                    'attributes' => [
                        self::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                        self::EVENT_BEFORE_UPDATE => ['updated_at'],
                    ],
                    'value' => new Expression('NOW()'),
                ],

            ];

    }
}