<?php
/**
 * Created by PhpStorm.
 * User: Hpp
 * Date: 15.07.2018
 * Time: 0:55
 */

namespace frontend\modules\api\controllers;


use common\models\Task;
use common\models\User;
use yii\data\ActiveDataProvider;
use yii\filters\auth\HttpBasicAuth;
use yii\rest\ActiveController;
use yii\web\ForbiddenHttpException;

class TaskController extends ActiveController
{
    public $modelClass = Task::class;

    public function behaviors()
    {
//        return parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => HttpBasicAuth::className(),
            'auth' => function ($username, $password) {
                $user = User::findByUsername($username);
                if ($user !== NULL && $user->validatePassword($password)) {
                    return $user;
                }
                return null;
            }
        ];
        return $behaviors;
    }

    public function actions()
    {
        parent::actions(); // TODO: Change the autogenerated stub
        $actions = parent::actions();
        unset($actions['index']);
        return $actions;
    }

    public function actionIndex()
    {
        $query = Task::find();
//        return parent::actions(); // TODO: Change the autogenerated stub
        $this->apiFilter($query);
        return new ActiveDataProvider([
            'query' => $query
        ]);
    }

  /*  public function checkAccess($action, $model = null, $params = [])
    {
//        parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub

        if (!\Yii::$app->user->id) {
            throw new ForbiddenHttpException();
        }
    }*/

    public function apiFilter($query)
    {
        if ($filter = \Yii::$app->request->get('filter')) {
            return $query->filterWhere([
                'name' => $filter['name'],
                'date' => $filter['date'],
                'status' => $filter['status'],
                'created_at' => $filter['created_at'],
            ]);
        }
    }


}